#+OPTIONS: num:nil toc:nil \n:t
#+LATEX: \setlength\parindent{0pt}
* Uppgift 3
** Uppgiften

*** Specifikation
 I ett tryckeri finns olika motorer och annan elutrustning som en elektriker en
 gång i tiden har kopplat in. I sin iver att göra allting ”riktigt bra” kopplade
 denne in en faskompenserande kondensator som var på tok för stor med avsikten
 ”att kunna växa och slippa köpa till extra kondensator senare då man skall
 utvidga”. Följande finns:
 -Lysrör på totalt 5.0 kW med cosφ = 0,707107 (ind)
 -Elmotorer på totalt 10 kW med cosφ = 0,80 (ind)
 -Vanliga resistiva elapparater (tex glödlampor, värmeelement, etc) på totalt
 5,5 kW (med cosφ = 1,0)
 -En faskompenserande kondensator på totalt 20 kVAr

 *Notera 5.0 kW och 10 kW*

*** A
a) Beräkna total aktiv effekt P, total reaktiv effekt Q, totalt skenbar effekt S
samt total effektfaktor cosφ är för befintlig anläggning.  Ledning: Observera
att cosφ blir kapacitiv (mot normalt induktiv)

*** B
 b) Företaget skall utvidga och man köper in 3 st nya elmotorer på vardera 10 kW
med cosφ = 0,8 (ind.). Efter inkopplingen skall totala effektfaktorn vara minst
0,95 (ind). OBS! Detta skall inte tolkas som 0,96 utan som 0,95 eller högre.
Beräkna den nya effektfaktorn. Behövs ytterligare faskompenserande kondensator
(utöver tidigare kondensator/kondensatorer) och hur stor skall i så fall denna
nya (extra kondensator) i så fall vara mätt i [kVAr]?

*** C
 c) En tid senare köper företaget in ytterligare 3 st nya elmotorer av samma
sort som i uppgift b). Efter inkopplingen skall totala effektfaktorn vara minst
0,95 (ind). OBS! Detta skall inte tolkas som 0,96 utan som 0,95 eller högre.
Beräkna den nya effektfaktorn. Behövs ytterligare faskompenserande kondensator
(utöver tidigare kondensator/kondensatorer) och hur stor skall i så fall denna
nya (extra kondensator) i så fall vara mätt i [kVAr]?

*** D
 d) Egenkontroll (som skall redovisas):  Summera nu ihop P och Q för alla
komponenter som nu finns efter uppgift c), dvs lysrör, elmotorer, resistiva
elapparater, original faskompenserande kondensator, 3 st nya Elmotorer,
eventuell extra faskompenserande kondensator, ytterligare 3 st nya Elmotorer
samt eventuell ytterligare extra faskompenserande kondensator.

(OBS! Summera allt från början. Utnyttja inte delresultat ovan!)Beräkna totala
cosφ igen och kontrollera att det blir 0,95. Om det inte blir 0,95 så gå igenom
beräkningarna igen innan du lämnar in. (Om du kör fast och inte hittar felet så
får du naturligtvis lämna in ändå för att få vägledning.)

** Lösning
*** A
Det finns lysrör på totalt 5.0 kW med PF 0.707107 (ind)
Det finns elmotorer på totalt 10 kW cos PF = 0.80 (ind)
Det finns vanliga resisitva elapparater på totalt 5.5 kW med PF = 1 (enbart resistiv)
En faskompenserande kondensator på totalt 20 kVAr

a) Beräkna total aktiv effekt P, total reaktiv effekt Q, totalt skenbar effekt S
samt total effektfaktor cosφ är för befintlig anläggning. Ledning: Observera att
cosφ blir kapacitiv (mot normalt induktiv)


$P (aktiv)   = UI * cos \phi W \;\;\; <=> S * cos \phi$
$S (skenbar) = UI$
$Q (reaktiv) = UI * sin \phi VAr \;\;\; <=> S * sin \phi$
$Q = P tan \phi$

$\phi = arccos(0.707107)$
$P_{lys} = 5.0 kW$ (lys = lysrör)
$Q_{lys} = 5.0 * tan(cos^{-1}(0.707107)) \approx 4.999 kVAr (ind)$

$\phi = arccos(0.8)$
$P_{elm} = 10 kW$ (elm = elmotorer)
$Q_{elm} = 10 * tan(cos^{-1}(0.8)) = 7.5 kVAr (ind)$

$\phi = arccos(1) = 0$
$P_{app} = 5.5 kW$ (app = vanliga resistiva elapparater)
$Q_{app} = 0 VAr$

För att räkna ut de totala effekterna börjar vi att med att addera P och Q var
för sig. Därifrån kan vi räkna ut S med hjälp av Pythagoras sats.

$P_{tot} = 5.0 kW + 10 kW + 5.5 kW = 20.5 kW$
$Q_{tot} = 4.999 kVAr + 7.5 kVAr + 0 VAr = 12.499 (ind)$

Men vi har även den faskompenserande kondensatorn på total 20 kVAr, så vi räknar
in det i $Q_{tot}$. Då den tillhör kapacitiv reaktans så drar jag bort det från
Q_{tot} som annars är induktiv.

$Q_{tot} = |12.499 (ind) - 20 kVAr (kap)| = 7.501 kVAr (kap)$

Därefter kan vi räkna ut S_{tot}.

$S_{tot} = \sqrt{P_{tot}^{2} + Q_{tot}^{2}}$
$S_{tot} = \sqrt{20.5^{2} + 7.501^{2}}$
$S_{tot} \approx 21.829 kVA$

Med hjälp av detta kan vi räkna ut cos \phi för anläggningen. Från
gymnasiematten kanske man vet att $cos \phi = närliggande / hypotenusa$, vilket i
det här fallet då är...

$cos \phi = \frac{P}{S}$
$cos \phi = \frac{20.5}{21.829}$
$cos \phi = 0.939 (kap)$

*Svar*: $P_{tot} = 20 kW$, $S_{tot} = 6 kVA$, $Q_{tot} = 7 kVAr (kap)$,
$cos \phi = 0.939 (kap)$.


** B
b) Företaget skall utvidga och man köper in 3 st nya elmotorer på vardera 10 kW
med cosφ = 0,8 (ind.). Efter inkopplingen skall totala effektfaktorn vara minst
0,95 (ind). OBS! Detta skall inte tolkas som 0,96 utan som 0,95 eller högre.
Beräkna den nya effektfaktorn. Behövs ytterligare faskompenserande kondensator
(utöver tidigare kondensator/kondensatorer) och hur stor skall i så fall denna
nya (extra kondensator) i så fall vara mätt i [kVAr]?

Innan uppgraderingen vet vi följande.
